name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check fmt
      run: cargo fmt --all -- --check
    - run: cargo check -p example

  readme:
    name: Check Readme
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: cargo install cargo-rdme
    - run: cargo rdme --check

  check_msrv:
    name: Check MSRV (1.77.0)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@1.77.0
    - run: cargo check -p example
